# Generated by Django 6.0.3 on 2026-04-04 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('boda', 'Boda'), ('graduacion', 'Graduación'), ('comunion', 'Comunión'), ('gala', 'Gala'), ('preboda', 'Preboda'), ('otro', 'Otro')], max_length=20)),
                ('fecha', models.DateField()),
                ('concepto', models.CharField(choices=[('cena', 'Cena'), ('comida', 'Comida'), ('barbacoa', 'Barbacoa'), ('cocktail', 'Cocktail'), ('otro', 'Otro')], max_length=20)),
                ('personas', models.PositiveIntegerField()),
                ('notas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('espacio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='core.espacio')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['fecha'],
            },
        ),
    ]
