# Generated by Django 6.0.3 on 2026-04-04 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_evento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='espacio',
        ),
        migrations.AddField(
            model_name='evento',
            name='espacios',
            field=models.ManyToManyField(related_name='eventos', to='core.espacio'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='concepto',
            field=models.CharField(choices=[('cena', 'Cena'), ('comida', 'Comida'), ('almuerzo', 'Almuerzo'), ('barbacoa', 'Barbacoa'), ('cocktail', 'Cocktail'), ('barra', 'Barra'), ('ceremonia', 'Ceremonia'), ('otro', 'Otro')], max_length=20),
        ),
    ]
