# Generated by Django 6.0.3 on 2026-04-07 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_evento_espacio_evento_espacios_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticuloPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('espacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articulos', to='core.espacio')),
            ],
            options={
                'verbose_name': 'Artículo de pedido',
                'verbose_name_plural': 'Artículos de pedido',
                'ordering': ['nombre'],
            },
        ),
    ]
