# Generated by Django 6.0.3 on 2026-04-08 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_nota'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='eventos/documentos/')),
                ('nombre', models.CharField(blank=True, max_length=200)),
                ('subido', models.DateTimeField(auto_now_add=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='core.evento')),
            ],
            options={
                'ordering': ['-subido'],
            },
        ),
    ]
