# Generated by Django 6.0.3 on 2026-04-12 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_eventodocumento'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='plano_json',
            field=models.TextField(blank=True, default=''),
        ),
    ]
