# Generated by Django 6.0.3 on 2026-04-12 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_evento_plano_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoRango',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('camarero', models.CharField(blank=True, max_length=100)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rangos', to='core.evento')),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
    ]
