# Generated by Django 6.0.3 on 2026-04-12 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_eventorango'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventorango',
            name='camarero',
        ),
        migrations.CreateModel(
            name='EventoCamarero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('rango', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camareros', to='core.eventorango')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
