# Generated by Django 6.0.3 on 2026-04-12 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_eventocamarero'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventocamarero',
            name='funcion',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
