# Generated by Django 6.0.3 on 2026-04-21 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_camarero_funcion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nota',
            options={'ordering': ['resuelta', 'prioridad', '-fecha'], 'verbose_name': 'Nota', 'verbose_name_plural': 'Notas'},
        ),
        migrations.AddField(
            model_name='nota',
            name='prioridad',
            field=models.CharField(choices=[('urgente', 'Urgente'), ('moderado', 'Moderado'), ('normal', 'Normal')], default='normal', max_length=10),
        ),
        migrations.AddField(
            model_name='nota',
            name='resuelta',
            field=models.BooleanField(default=False),
        ),
    ]
