# Generated by Django 6.0.3 on 2026-04-27 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_nota_options_nota_prioridad_nota_resuelta'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='evento',
            name='fecha_eliminado',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
