# Generated by Django 6.0.3 on 2026-04-05 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_remove_evento_espacio_evento_espacios_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TareaPlantilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('momento', models.CharField(choices=[('apertura', 'Apertura'), ('cierre', 'Cierre')], max_length=10)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
                ('espacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas_plantilla', to='core.espacio')),
            ],
            options={
                'verbose_name': 'Tarea plantilla',
                'verbose_name_plural': 'Tareas plantilla',
                'ordering': ['espacio', 'momento', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='TareaDelDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('completada', models.BooleanField(default=False)),
                ('completada_por', models.CharField(blank=True, max_length=100)),
                ('hora_completada', models.TimeField(blank=True, null=True)),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instancias', to='tareas.tareaplantilla')),
            ],
            options={
                'verbose_name': 'Tarea del día',
                'verbose_name_plural': 'Tareas del día',
                'ordering': ['fecha', 'plantilla__momento', 'plantilla__orden'],
            },
        ),
    ]
