# Generated by Django 6.0.3 on 2026-04-05 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_remove_evento_espacio_evento_espacios_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(blank=True, max_length=100)),
                ('rol', models.CharField(choices=[('maitre', 'Maître'), ('jefe_sector', 'Jefe de sector'), ('camarero', 'Camarero')], max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('horas', models.PositiveIntegerField(default=0)),
                ('estado', models.CharField(choices=[('trabajo', 'Trabajo'), ('libre', 'Día libre'), ('inamovible', 'Inamovible'), ('vacaciones', 'Vacaciones'), ('libre_vacaciones', 'Libre vacaciones'), ('finde_largo', 'Finde largo'), ('baja', 'Baja')], default='trabajo', max_length=20)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='personal.empleado')),
                ('espacio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos', to='core.espacio')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'ordering': ['fecha', 'empleado'],
            },
        ),
    ]
