# Generated by Django 6.0.3 on 2026-04-07 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='rol',
            field=models.CharField(choices=[('maitre', 'Maître'), ('segundo_maitre', 'Segundo Maître'), ('jefe_sector', 'Jefe de sector'), ('camarero', 'Camarero'), ('ayudante_camarero', 'Ayudante de camarero')], max_length=20),
        ),
    ]
