# Generated by Django 6.0.3 on 2026-04-08 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_empleado_fecha_nacimiento_alter_empleado_rol'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={'ordering': ['posicion', 'nombre'], 'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados'},
        ),
        migrations.AddField(
            model_name='empleado',
            name='posicion',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='SolicitudAusencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('vacaciones', 'Vacaciones'), ('libre', 'Día libre'), ('inamovible', 'Libre inamovible'), ('libre_vacaciones', 'Libre vacaciones'), ('finde_largo', 'Finde largo')], default='vacaciones', max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('notas', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='personal.empleado')),
            ],
            options={
                'verbose_name': 'Solicitud de ausencia',
                'verbose_name_plural': 'Solicitudes de ausencia',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
