# Generated by Django 6.0.3 on 2026-04-08 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_alter_empleado_options_empleado_posicion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='tipo_contrato',
            field=models.CharField(blank=True, choices=[('indefinido', 'Indefinido'), ('temporal', 'Temporal'), ('fijo_discontinuo', 'Fijo discontinuo'), ('obra_servicio', 'Obra y servicio'), ('practicas', 'Prácticas')], max_length=20),
        ),
    ]
