# Generated by Django 6.0.3 on 2026-05-19 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_empleado_fecha_vencimiento_empleado_tipo_contrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='color_override',
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
