# Generated by Django 6.0.3 on 2026-05-01 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_empleado_fecha_vencimiento_empleado_tipo_contrato'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoraExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('motivo', models.CharField(max_length=200)),
                ('horas', models.DecimalField(decimal_places=1, max_digits=4)),
                ('pagadas', models.BooleanField(default=False)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horas_extra', to='personal.empleado')),
            ],
            options={
                'verbose_name': 'Hora extra',
                'verbose_name_plural': 'Horas extra',
                'ordering': ['-fecha'],
            },
        ),
    ]
