# Generated by Django 6.0.3 on 2026-05-19 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0005_color_override_turno'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='color',
            field=models.CharField(default='#16a34a', max_length=7),
        ),
    ]
