# Generated by Django 6.0.3 on 2026-05-19 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0006_color_empleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='horas_semana',
            field=models.PositiveIntegerField(default=40),
        ),
    ]
