# Generated by Django 6.0.3 on 2026-09-26 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0005_hora_extra'),
        ('personal', '0007_horas_semana_empleado'),
    ]

    operations = [
    ]
